const actionTypes = {
    GET_HOME: 'GET_HOME',
    SET_CUR_SONG_ID: 'SET_CUR_SONG_ID',
    LOADING: 'LOADING',
    SET_CUR_SONG_DATA: 'SET_CUR_SONG_DATA',
    SET_CUR_PLAYLIST_ID: 'SET_CUR_PLAYLIST_ID',
    SET_RECENT: 'SET_RECENT',
    CURRENT_WIDTH: 'CURRENT_WIDTH',
    SET_RECENT_PLAYLIST: 'SET_RECENT_PLAYLIST',
    

    // Music
    PLAY: 'PLAY',
    SET_ALBUM: 'SET_ALBUM',
    PLAYLIST: 'PLAYLIST',
    SEARCH: 'SEARCH',
}

export default actionTypes